spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false

kakao:
  tokenUrl: https://kauth.kakao.com/oauth/token
  userApiUrl: https://kapi.kakao.com/v2/user/me
  restapiKey: 0efff2c2f5f7de603b91cb6230b131ab
  redirectUrl:  http://localhost:8080/callback
  authUrl: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=